# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d327da2f6bf48374968c7afa62bba655673bb8c942814fc6bb99e2987ec59c9c5dbffe6f3586f97810a08510136082e937d20c95ccfe98b4864d487d21248e9

test:
  secret_key_base: 49666ce5efc429db5c2f7df884d9beb284e644be3a686bf314e56e84e36df34ae0758e062bfc158cabd46083c4c4c0aeba326f5672bf69597990f4927ac698b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
